### ISSUE TITLE
建議：修改部件

### ISSUE THREAD

**Issue by UltimateAmitieKaiNiC** [max32002/kurewa-gothic#1]
眾下邊的是三人，聚下方部分需要修改一下，比如「驟」「鄹」等部分。
![image](https://user-images.githubusercontent.com/67255901/123588297-223b6800-d81a-11eb-9d8b-0ced6cbde7fb.png)

**Comment by max32002** [comment]
2021/06/29 ver 1.052
更新 CJK TC 裡的中文字如下：聚驟

**Comment by UltimateAmitieKaiNiC** [comment]
【揄】出了BUG，還有部分的戶沒修改

**Comment by max32002** [comment]
> 【揄】出了BUG，還有部分的戶沒修改

請改服用 ver 1.053 版。

**Comment by UltimateAmitieKaiNiC** [comment]
像是「偏」「遍」等戶部件沒改

**Comment by max32002** [comment]
> 像是「偏」「遍」等戶部件沒改

請改服用 ver 1.054 版。

**Comment by UltimateAmitieKaiNiC** [comment]
有部分的字重粗細反了，例如“夢”的部分

**Comment by max32002** [comment]
已解決，請服用 1.056 版。

![Screen Shot 2021-11-22 at 10 09 03 AM](https://user-images.githubusercontent.com/4498233/142790795-93982078-38d1-4b55-9816-a4626f53c42d.png)

**Comment by UltimateAmitieKaiNiC** [comment]
“包”有部分仍舊是日本字形

**Comment by max32002** [comment]
請更新到 1.058 版，謝謝。
<img width="614" alt="Screen Shot 2021-11-26 at 6 31 13 PM" src="https://user-images.githubusercontent.com/4498233/143567048-c045516c-4447-4594-ae64-4572b697dba4.png">

**Comment by UltimateAmitieKaiNiC** [comment]
歡字有部分字重相反

**Comment by max32002** [comment]
ver 1.071, 更新: 爸繭罐舊讙護歡敬穫寬檠薨襪鑵顴橫

![Screen Shot 2022-09-22 at 2 29 31 PM](https://user-images.githubusercontent.com/4498233/191677352-a6302a17-38fa-4fc1-862c-24080d8f59ed.png)
