### ISSUE TITLE
ZEN系列字体版权

### ISSUE THREAD

**Issue by TimeSheepY** [max32002/kurewa-gothic#2]
![QQ图片20210704164131](https://user-images.githubusercontent.com/59170247/124378920-b90a9780-dce6-11eb-9d5b-713ad67c7b09.jpg)

**Comment by TimeSheepY** [comment]
info@zenfont.jp这是邮件地址。

**Comment by max32002** [comment]
目前已開源，沒有授權的問題。感謝Mike熱心提醒。
